spring.application.name=smartqueue
spring.datasource.url=jdbc:mysql://localhost:3306/smartqueuedb
spring.datasource.username=root
spring.datasource.password=Yoga@2006

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true